Repository sumoheavy/jira-ruby, pull requests merged in 2024-04, with the labels that each got.

#407 chore(gems): Upgrade to OAuth 1.x
  jira-ruby.gemspec
Labels: Maintenance

#422 Attachment download contents
  lib/jira/resource/attachment.rb
  spec/jira/resource/attachment_spec.rb
Labels: Enhancement

#417 Update README.md to include useage examples in the example.rb file
  README.md
Labels: Documentation

#412 Moves JWT to headers instead of query string
  lib/jira/jwt_client.rb
  spec/jira/client_spec.rb
  spec/jira/jwt_uri_builder_spec.rb
Labels: Enhancement

#438 #430 Upgrade webmock and tests
  jira-ruby.gemspec
  spec/jira/client_spec.rb
  spec/support/clients_helper.rb
Labels: Maintenance

#355 Switch to new sprint interface
  lib/jira/resource/sprint.rb
Labels: Enhancement

#447 Bump version to prepare for the next release
  lib/jira/version.rb
Labels: Maintenance

#445 Add tests for sprints and fix complete_date
  lib/jira-ruby.rb
  lib/jira/client.rb
  lib/jira/resource/sprint.rb
  lib/jira/resource/sprint_report.rb
  spec/jira/resource/sprint_spec.rb
  spec/mock_responses/sprint/1.json
Labels: Bug, Enhancement
